[project]
name = "senior_softwer_developer_for_create_and_testing_and_writing_code"
version = "0.1.0"
description = "Senior_softwer_developer_for_create_and_testing_and_writing_code using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.14.4",
    "litellm"
]

[project.scripts]
senior_softwer_developer_for_create_and_testing_and_writing_code = "senior_softwer_developer_for_create_and_testing_and_writing_code.main:run"
run_crew = "senior_softwer_developer_for_create_and_testing_and_writing_code.main:run"
train = "senior_softwer_developer_for_create_and_testing_and_writing_code.main:train"
replay = "senior_softwer_developer_for_create_and_testing_and_writing_code.main:replay"
test = "senior_softwer_developer_for_create_and_testing_and_writing_code.main:test"
run_with_trigger = "senior_softwer_developer_for_create_and_testing_and_writing_code.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
